import OpenAI from "openai"
import { sanitizeInput } from "./sanitizeInput"
import { filterContent } from "./filterContent"
import { formatLyrics } from "./formatLyrics"

type GenerateLyricsOptions = {
  concept: string
  openai: OpenAI
  maxTokens?: number
}

export async function generateLyricsCore({
  concept,
  openai,
  maxTokens = 500,
}: GenerateLyricsOptions): Promise<string> {
  if (!concept || typeof concept !== "string" || !concept.trim()) {
    throw new Error("Valid concept is required")
  }

  // Sanitize user input
  const sanitizedConcept = sanitizeInput(concept)

  // Generate lyrics
  const response = await openai.chat.completions.create({
    model: "gpt-5.2",
    messages: [
      {
        role: "system",
        content:
          "You are a talented rapper and R&B songwriter. Create lyrics based on the given concept or story. Avoid explicit content or offensive language.",
      },
      {
        role: "user",
        content: `Write rap or R&B lyrics based on this concept: ${sanitizedConcept}`,
      },
    ],
    max_tokens: maxTokens,
  })

  const generatedLyrics = response.choices[0]?.message?.content

  if (!generatedLyrics) {
    throw new Error("No lyrics were generated by the AI")
  }

  const formattedLyrics = formatLyrics(generatedLyrics)

  // Apply content filtering
  return filterContent(formattedLyrics)
}
