import OpenAI from "openai"
import { sanitizeInput } from "./sanitizeInput"
import { filterContent } from "./filterContent"
import { formatLyrics } from "./formatLyrics"

type GenerateLyricsOptions = {
  concept: string
  openai: OpenAI
  maxTokens?: number
}

export async function generateLyricsCore({
  concept,
  openai,
  maxTokens = 500,
}: GenerateLyricsOptions): Promise<string> {
  if (!concept || typeof concept !== "string" || !concept.trim()) {
    throw new Error("Valid concept is required")
  }

  // Sanitize user input
  const sanitizedConcept = sanitizeInput(concept)

  // Generate lyrics using the Responses API (required for gpt-5.2)
  const response = await openai.responses.create({
    model: "gpt-5.2",
    input: [
      {
        role: "system",
        content: [
          {
            type: "input_text",
            text: "You are a talented rapper and R&B songwriter. Create lyrics based on the given concept or story. Avoid explicit content or offensive language.",
          },
        ],
      },
      {
        role: "user",
        content: [
          {
            type: "input_text",
            text: `Write rap or R&B lyrics based on this concept: ${sanitizedConcept}`,
          },
        ],
      },
    ],
    max_output_tokens: maxTokens,
  })

  const generatedLyrics = response.output
    ?.map((item) => {
      if (!("content" in item) || !Array.isArray(item.content)) {
        return ""
      }

      return item.content
        .map((part) => (part.type === "output_text" ? part.text ?? "" : ""))
        .join("")
    })
    .join("")
    .trim()

  if (!generatedLyrics) {
    throw new Error("No lyrics were generated by the AI")
  }

  const formattedLyrics = formatLyrics(generatedLyrics)

  // Apply content filtering
  return filterContent(formattedLyrics)
}
